version: '3'
services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  atassauth:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - redis-stack-server
