version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./test.json:/app/test.json
