name: code-testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run unit tests for registration
        run: go test ./tests/unit/registration
      - name: Run unit tests for password resetting
        run: go test ./tests/unit/resetpassword

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          only-new-issues: true

  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start services
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose-local.yml"
          services: |
            redis
            app
      - name: Install Python and pytest
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r tests/requirements.txt
      - name: Run end-to-end tests
        run: pytest tests/e2e_test.py
      - name: Stop services
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose-local.yml"
          down-flags: "--volumes"
          services: |
            redis
            app
          
  docker:
    name: Publishes to Docker Hub
    runs-on: ubuntu-latest
    needs: [test, golangci, e2e]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gaponukz/atassauth:latest
