name: e2e

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run end-to-end tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server:latest
        ports:
          - 6379:6379
        options: --name redis-stack-server

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: Start test Go app
        run: go run cmd/test/main.go &

      - name: Install Python and pytest
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run end-to-end tests
        run: pytest tests/e2e_test.py
